obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
#robot_radius: ir_of_robot
robot_radius: 0.3 # distance a circular robot should be clear of the obstacle
inflation_radius: 0.3

observation_sources: laser_scan_sensor #point_cloud_sensor

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {sensor_frame: zed_center, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
