DWAPlannerROS:
  acc_lim_x: 0.1
  acc_lim_y: 0
  acc_lim_th: 0.05
  max_trans_vel: 1.0
  min_trans_vel: 0.0
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_y: 0
  min_vel_y: 0
  max_rot_vel: 0.6
  min_rot_vel: 0.0

  yaw_goal_tolerance: 0.7
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

  sim_time: 1.5
  sim_granularity: 0.025
  vx_samples: 10
  vy_samples: 0
  vtheta_samples: 20
  controller_frequency: 10
  penalize_negative_x: true

  path_distance_bias: 1.0
  goal_distance_bias: 0.8
  occdist_scale: 0.01
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 1
  max_scaling_factor: 0.2

  oscillation_reset_dist: 0.05

  prune_plan: false  

  sim_period: 0.1
  rot_stopped_vel: 0.01
  trans_stopped_vel: 0.01
